### ISSUE TITLE
Vertical Metrics

### ISSUE THREAD

**Issue by m4rc1e** [cyrealtype/Prata#4]
local vs google api.

![screen shot 2016-11-14 at 13 34 56](https://cloud.githubusercontent.com/assets/7525512/20265075/3b79125a-aa6f-11e6-83bb-2c72c3b97645.png)

Your choice whether to regress or not.

**Comment by alexeiva** [comment]
my choice is the version on the left. 

right is too tight.

**Comment by alexeiva** [comment]
Closing this, since no action is required.
